### ISSUE TITLE
TransitivePropertyAccessor infinite loop (and OutOfMemory)

### ISSUE THREAD

**Issue by IgorRodchenkov** [BioPAX/Paxtools#1]
The issue seems to occur when converting the large PC2v8 biopax model to GSEA or SIF. 
It still needs to be confirmed where exactly, but looks like it's either in gsea-converter or, highly possible, in  biopax pattern module (which uses transitive property paths a lot, e.g., "PhysicalEntity/controllerOf/controlled*:Interaction", etc.)...

Exception in thread "pool-2-thread-3" java.lang.StackOverflowError
        at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:130)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:114)
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:415)
        at java.lang.StringBuilder.append(StringBuilder.java:132)
        at java.lang.Class.toString(Class.java:151)
        at java.lang.String.valueOf(String.java:2854)
        at java.lang.StringBuilder.append(StringBuilder.java:128)
        at org.biopax.paxtools.impl.BioPAXElementImpl.hashCode(BioPAXElementImpl.java:224)
        at java.util.HashMap.hash(HashMap.java:366)
        at java.util.HashMap.put(HashMap.java:496)
        at java.util.HashSet.add(HashSet.java:217)
        at org.biopax.paxtools.controller.TransitivePropertyAccessor.transitiveGet(TransitivePropertyAccessor.java:40)
        at org.biopax.paxtools.controller.TransitivePropertyAccessor.transitiveGet(TransitivePropertyAccessor.java:42)
        at org.biopax.paxtools.controller.TransitivePropertyAccessor.transitiveGet(TransitivePropertyAccessor.java:42)
        at org.biopax.paxtools.controller.TransitivePropertyAccessor.transitiveGet(TransitivePropertyAccessor.java:42)
        at org.biopax.paxtools.controller.TransitivePropertyAccessor.transitiveGet(TransitivePropertyAccessor.java:42)
...

It's in the recursive method private void transitiveGet(D bean, Set<R> values)
I think, the biopax model may contain circles/loops, such as a complex contains itself (perhaps those do not have much sense and have to be fixed by the validator), but transitiveGet method must survive and handle this anyway.

**Comment by IgorRodchenkov** [comment]
Emek's fixed this one.
