### ISSUE TITLE
Cannot add a new EntityReference

### ISSUE THREAD

**Issue by metincansiper** [BioPAX/Paxtools#47]
**Minimum code to reproduce**
```
BioPAXFactory factory = BioPAXLevel.L3.getDefaultFactory();
Model model = factory.createModel();
model.addNew(EntityReference.class, "3d8d8d63-997e-4967-9469-0da3f691f659");
```

**Error**
For version ``5.2.1-SNAPSHOT``:

```
18:21:48.865 [main] INFO org.biopax.paxtools.util.BPCollections - System property: paxtools.CollectionProvider=null
18:21:48.867 [main] INFO org.biopax.paxtools.util.BPCollections - Using the default CollectionProvider (creates HashMap, HashSet).
18:21:48.871 [main] ERROR org.biopax.paxtools.model.BioPAXFactory - Failed creating BioPAX object: interface org.biopax.paxtools.model.level3.EntityReference, URI: 3d8d8d63-997e-4967-9469-0da3f691f659
java.lang.InstantiationException: null
	at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.biopax.paxtools.model.BioPAXFactory.create(BioPAXFactory.java:76)
	at org.biopax.paxtools.impl.ModelImpl.addNew(ModelImpl.java:120)
	at factoid.model.TemplatesModel.main(TemplatesModel.java:254)
Exception in thread "main" java.lang.NullPointerException
	at org.biopax.paxtools.impl.ModelImpl.add(ModelImpl.java:158)
	at org.biopax.paxtools.impl.ModelImpl.addNew(ModelImpl.java:121)
	at factoid.model.TemplatesModel.main(TemplatesModel.java:254)
```

For version ``5.1.0``:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NullPointerException
	at org.biopax.paxtools.impl.ModelImpl.add(ModelImpl.java:158)
	at org.biopax.paxtools.impl.ModelImpl.addNew(ModelImpl.java:121)
	at BiopaxExp.BiopaxExp.Main.main(Main.java:14)
```

**Debugging observations so far**
![IMG_5059](https://user-images.githubusercontent.com/6534865/77975148-1a56e600-72ae-11ea-87c4-52387f56a135.jpg)

As it is show in the screenshot above ``constructorAccessor`` property is set to ``instantiationexceptionconstructoraccessorimpl`` while it is set to ``delegetingconstructoraccessorimpl`` for the other element types that I tried so far and was able to add with success (e.g. Interaction).

**Comment by IgorRodchenkov** [comment]
Metin, as I recall, EntityReference is not instantiable class/interface, use a subclass instead. Ask Emek.

IR

**Comment by IgorRodchenkov** [comment]
It’s not a bug, but feature - you should not do this.

IR

**Comment by metincansiper** [comment]
Thank you Igor! That helped me figure out what was going on.

Looks like we were already using the subclasses ``ProtenReference`` and ``SmallMoleculeReference`` in related cases. ``EntityReferece`` was being used where there is no match since we probably assumed that it is instantiable  . Probably, after some changes in factoid side that no match case is executed and ``EntityReferece`` is attempted to be instantiated. If ``EntityReferece`` is not instantiable then I will probably handle that case as an exception accordingly and make the changes for compability between the converter and factoid.
